config:
  send_anonymous_usage_stats: False

global_superstore:
  target: dev
  outputs:
    dev: # User-Password config
      type: snowflake
      account: your-snowflake-account-id-here
      user: DEV_DBT_CLOUD
      password: your-password-here
      role: DEV_DBTDE_CLOUD
      database: DEV
      warehouse: DEV_CLOUD_ANALYTICS
      schema: dbt_your-username-here
      threads: 2
      client_session_keep_alive: False
    PROD: # User-Password config
      type: snowflake
      account: your-snowflake-account-id-here
      user: PROD_DBT_CLOUD
      password: your-password-here
      role: PROD_DBTDE_CLOUD
      database: PROD_ANALYTICS
      warehouse: PROD_CLOUD_ANALYTICS
      schema: dbt_your-username-here
      threads: 2
      client_session_keep_alive: False
