{{ config(
    materialized = "table",
    schema = "master_data"
)}}


WITH CTE_MY_DATE AS (
    SELECT DATEADD(DAY, SEQ4(), '2012-01-01') AS MY_DATE
      FROM TABLE(GENERATOR(ROWCOUNT=>1461)))

  SELECT DATE(MY_DATE) AS CAL_DT
        ,YEAR(MY_DATE) AS FISCAL_YEAR
        ,MONTH(MY_DATE) AS FISCAL_MONTH_NUM
        ,TO_CHAR(MY_DATE,'MMMM') AS FISCAL_MONTH_FULL_NAME
        ,DAYOFWEEK(MY_DATE) AS DAY_OF_WEEK
        ,DAYOFYEAR(MY_DATE) AS DAY_OF_YEAR
    FROM CTE_MY_DATE