version: 2

models:
  - name: global_customer_dim
    description: Customer Dimension Table
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - customer_id
            - state
            - city
            - postal_code
    columns:
    - name: CUSTOMER_ID
      description: Customer Id
    - name: CUSTOMER_NAME
      description: Customer Name
    - name: POSTAL_CODE
      description: Postal Code
    - name: CITY
      description: City
    - name: STATE
      description: STATE
    - name: COUNTRY
      description: COUNTRY
    - name: RECORD_CREATED_DATETIME
      description: Record Created Date time
  
  - name: global_product_dim
    description: Product dimension table
    columns:
    - name: PRODUCT_ID
      description: Unique Product Id
      tests:
        - unique
        - not_null
    - name: PRODUCT_NAME
      description: Product Name
    - name: PRODUCT_CATEGORY
      description: Product Category
    - name: PRODUCT_SUB_CATEGORY
      description: Product SubCategory
    - name: RECORD_CREATED_DATETIME
      description: Record Created Date time
  
  - name: calendar_dim
    description: Calendar Dimension Table
    columns:
    - name: cal_dt
      description: Calendar Date
    - name: fiscal_year
      description: Fiscal Year
    - name: fiscal_month
      description: Fiscal Month of the Year
    - name: fiscal_month_full_name
      description: Fiscal Month Full Name
    - name: day_of_week
      description: Day of the Week
    - name: day_of_year
      description: Day of Year
    - name: current_year
      description: Current Year Indicator
    - name: is_leap_year
      description: Leap Year Indicator Flag
    - name: fiscal_month_start_dt
      description: Fiscal Month Start Date
    - name: fiscal_month_end_dt
      description: Fiscal Month End Date
  
  - name: global_sales_person_dim
    description: Sales Person Dimension Table
    columns:
    - name: sales_person_name
      description: Sales Person Name
      tests:
        - unique
    - name: sales_person_region
      description: Sales Person Region
    - name: record_created_datetime
      description: Record Created Date time

  - name: global_sales_returns
    description: Global Sales Returns Table
    columns:
    - name: returned
      description: returned
    - name: order_id
      description: Order Id
      tests:
        - unique
    - name: region
      description: region
    - name: record_created_datetime
      description: Record Created Date time

  - name: global_superstore_sales_fact
    description: Global Superstore Sales fact table
    columns:
    - name: row_id
      description: Unique row_id
      tests:
        - unique
    - name: order_id
      description: Order id
    - name: order_date
      description: Order date
    - name: ship_date
      description: Ship date
    - name: customer_id
      description: customer id
    - name: customer_name
      description: customer name
    - name: segment
      description: segment
    - name: postal_code
      description: postal code
    - name: city
      description: city
    - name: state
      description: state
    - name: country
      description: country
    - name: region
      description: region
    - name: market
      description: market
    - name: product_id
      description: product id
    - name: product_name
      description: product name
    - name: sales
      description: sales
    - name: quantity
      description: quantity
    - name: discount
      description: discount
    - name: profit
      description: profit
    - name: shipping_cost
      description: shipping cost
    - name: order_priority
      description: order priority
    - name: record_created_datetime
      description: Record Created Date time
  
  - name: global_superstore_summary_fact
    description: Global Superstore summary fact table
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - product_id
            - country
            - state
            - fiscal_month
    columns:
    - name: fiscal_year
      description: fiscal year
    - name: fiscal_month
      description: fiscal month
    - name: fiscal_month_end_dt
      description: fiscal month end date
    - name: current_year
      description: Current Year column which depicts value based on year of current date
    - name: product_id
      description: Product id
    - name: product_category
      description: product category
    - name: product_sub_category
      description: product subcategory
    - name: state
      description: state
    - name: region
      description: region
    - name: country
      description: country
    - name: market
      description: market
    - name: sales_person_name
      description: sales person name
    - name: rate_of_return
      description: Rate of Return based on the Sales Return data
    - name: Month_to_month_change
      description: Month to Month Change in Sales Value
    - name: Month_to_Month_change_pct
      description: Month to Month Change of sales value percentage
    - name: category_wise_sales_growth
      description: Category wise sales growth
    - name: category_wise_sales_growth_pct
      description: category wise sales growth percentage
    - name: sales_person_yearly_objective_sales
      description: sales person yearly objective sales
    - name: sales_value
      description: Sales Value
    - name: Sales Returns
      description: Sales Returns
    - name: Discount
      description: Discount
    - name: Profit
      description: Profit
    - name: quantity
      description: quantity
    - name: shipping_cost
      description: shipping_cost
    - name: revenue_per_sale
      description: Revenue per sale
    - name: last_refresh_datetime
      description: last refresh date timestamp