version: 2

models:
  - name: global_customer_dim
    description: Customer Dimension Table
    columns:
    - name: CUSTOMER_ID
      description: Customer Unique Id
    - name: CUSTOMER_NAME
      description: Customer Name
    - name: POSTAL_CODE
      description: Postal Code
    - name: CITY
      description: City
    - name: STATE
      description: STATE
    - name: COUNTRY
      description: COUNTRY
  
  - name: global_product_dim
    description: Product dimension table
    columns:
    - name: PRODUCT_ID
      description: Unique Product Id
      tests:
        - unique
        - not_null
    - name: PRODUCT_NAME
      description: Product Name
    - name: PRODUCT_CATEGORY
      description: Product Category
    - name: PRODUCT_SUB_CATEGORY
      description: Product SubCategory
  
  - name: calendar_dim
    description: Calendar Dimension Table
    columns:
    - name: cal_dt
      description: Calendar Date
    - name: fiscal_year
      description: Fiscal Year
    - name: fiscal_month
      description: Fiscal Month of the Year
    - name: fiscal_year_week
      description: Fiscal Year week
  
  - name: global_sales_person_dim
    description: Sales Person Dimension Table
    columns:
    - name: sales_person_name
      description: Sales Person Name
    - name: sales_person_region
      description: Sales Person Region
    
  - name: global_superstore_sales_fact
    description: Global Superstore Sales fact table
    columns:
    - name: row_id
      description: Unique row_id
    - name: order_id
      description: Order id
    - name: order_date
      description: Order date
    - name: ship_date
      description: Ship date
    - name: customer_id
      description: customer id
    - name: customer_name
      description: customer name
    - name: segment
      description: segment
    - name: postal_code
      description: postal code
    - name: city
      description: city
    - name: state
      description: state
    - name: country
      description: country
    - name: region
      description: region
    - name: market
      description: market
    - name: product_id
      description: product id
    - name: product_name
      description: product name
    - name: sales
      description: sales
    - name: quantity
      description: quantity
    - name: discount
      description: discount
    - name: profit
      description: profit
    - name: shipping_cost
      description: shipping cost
    - name: order_priority
      description: order priority